# Generated by Django 4.0.5 on 2023-05-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Ảnh',
            new_name='image',
        ),
    ]
